### PR TITLE
initial fastlane structure

### PR DESCRIPTION
**Pull request by IzzySoft**
Metadata as discussed in #1 – be welcome to use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) to build on this (e.g. replace screenshots, update description, add a featureGraphic, add per-release changelogs… whatever you feel needed).

### CODE REVIEW

**Comment by N0-0NE-Dev** [comment]
Thanks again!

**Comment by IzzySoft** [comment]
So where is it gone now? Since today it's no longer available. Strangely, I cannot find a commit removing it. But when I follow up the linked commit, it gives a warning that "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."

What happened, @N0-0NE-Dev? Will it reappear? Did you rewrite history and it got lost?

**Comment by N0-0NE-Dev** [comment]
> Did you rewrite history and it got lost?
Yeah that exactly what I did, I rewrote the app in bare react native instead of using expo to reduce the app size, improve performance and reduce the amount of permissions needed and in the process I forgot to add the fastlane files to the new branch.

> Will it reappear?
Yeah I will add the fastlane files now.

**Comment by IzzySoft** [comment]
Thanks a lot! My updater just complained today :rofl:

**Comment by N0-0NE-Dev** [comment]
> Curious for the new size then (currently it still seems the 19 MB per APK it had before).

It used to be closer to 25MB on versions before 1.1.9.

**Comment by IzzySoft** [comment]
> It used to be closer to 25MB on versions before 1.1.9.

Ah, then I just didn't look "down" far enough. So "fantastic" to get squared then, good job! :star_struck:

**Pull request merged**
